# numpy complete

 numpy is the foundamental packagee for scientific computing in python.
numpy is a python library that provides a multidimensions array object,various derived objects.

an array is grid of values and it contains information about the raw data how to locate an element and how to interpet an element

# numpy vs python list

**advantage of using numpy array over python lists:**

 1. consumes less memory .
 2. fast as compare t othe python lists .
 3. conenient to use.

In [1]:
import numpy as np

In [4]:
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
y=[1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [6]:
l=[]
for i in range(1,5):
    n=input("enter the number:")
    l.append(n)
print(np.array(l))

enter the number:4
enter the number:12
enter the number:12
enter the number:12
['4' '12' '12' '12']


In [7]:
l=[]
for i in range(1,5):
    n= int(input("enter the number:"))
    l.append(n)
print(np.array(l))

enter the number:3
enter the number:12
enter the number:13
enter the number:14
[ 3 12 13 14]


In [9]:
y=np.array([1,2,3,4])
print(y)
print(y.ndim)

[1 2 3 4]
1


# special numpy array

1. array filled with 0's
2. array filled with 1's
3. create an empty array
4. an array with a range of element
5. array diagonal ellement filled with 1's
6. create an array with values that are spaced linearly in a specified interval

# zeros

In [10]:
n=np.zeros(4)
print(n)

[0. 0. 0. 0.]


# ones

In [11]:
n=np.ones(5)
print(n)

[1. 1. 1. 1. 1.]


In [12]:
n=np.empty(4)
print(n)

[0. 0. 0. 0.]


# range

In [13]:
n=np.arange(4)
print(n)

[0 1 2 3]


# diagonal

In [14]:
n=np.eye(4)
print(n)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
n=np.eye(3,5)
print(n)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# create numpy array with random numbers

**rand():** the function is used to generated a rondom value between 0 to 1

In [17]:
n=np.random.rand()
print(n)

0.3810294512729675


**randn():** the function is used togenrate a rondom value close to zero   this  may reyrun +ve  or -ve numbers as well.

In [ ]:
**ranf():** the function for doing random sampling in numpy . it   

# NUMPY

numpy is python library was created in 2005 by travis oliphant numpy is used for working will arrays.
numpy aims to provided an array thai is up to 50x faster than traditional python list.


import numpy 
arr= numpy.array([1,2,3,4,5])
print(arr)

import numpy as np 
arr= np.array([1,2,3,4,5])
print(arr)

print(np.__version__)

print(type(arr))

# zero D array

import numpy as np
arr=np.array(40)
print(arr)
print(ndim(arr))

# 1 D array

import numpy as np
arr=np.array([40,34,6,4])
print(arr)
print(arr.ndim)
print(arr[0])

# 2D array

import numpy as np
arr=np.array([[40,34,6,4] ,[54,6,3,2]])
print(arr)
print(arr.ndim)

# 3D array

a=np.array(43)
b=np.array(45)
c=np.array(67)
d=np.array([[[1,2,3],[4,5,6],[7,8,9],[4,6,7]]])
print(a)
print(b)
print(c)
print(d)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(d.ndim)

# Indexing array 

arr=[2,4,3,2]
print(arr[0])

# Access 2D Arrays

import numpy as np
arr=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr)
print(arr[0,1])
print(arr[1,4])
print(arr[1,1])

arr=np.array([[[1,2,3],[4,5,54],[7,8,9],[3,4,5]]])
print(arr)
print(arr[0,1,2])

a = np.zeros((2, 3, 4))
print(a)
array([[[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1,-1])

# return item fro m3 colum all rows

import numpy as np
arr1=np.array([[5,6,0],[2,5,7]])
arr2=np.array([[3,87,54],[76,43,23]])
print(arr1 +arr2)

arr1=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr1)
print("printing the array... ")
print(arr1[:,0])
print(arr1[:,1])
print(arr1[:,2])

# return any number odd rows and even colums



import numpy as np

arr1 = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(arr1)

print("\n Printing array of odd rows and even column")
arr2=arr1[0::2, 1::2]
print(arr2)


import numpy as np
a=np.array([1,2,3,4,9,6])
b=np.array([1,6,7,8,9,9])
print(np.where(a==b))

import numpy as np
arr=np.array([1,2,3,4,5,56,3,2])
print(arr[1:3])
print(arr[3:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:6:2])

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[0,1:2])
print(arr[:,1])
print(arr[0:2,2])
print(arr[0:2,1:4])



import numpy as np
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

import numpy as np
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

import numpy as np
arr=np.array([1.1,2.2,3.3,4.1])
new=arr.astype('i')
print(new)
print(new.dtype)

# copy and view

# copy

import numpy as np
arr=np.array([23,4,52,32,3])
x=arr.copy()
arr[0]=31
print(arr)
print(x)

# view

import numpy as np
arr=np.array([23,4,52,32,3])
x=arr.view()
arr[0]=31
print(arr)
print(x)

# shape

import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)
#2 dimension and 5 element

# reshape

# change  1D with 2D array

import numpy as np
arr= np.array([1,2,4,32434,4,2,6,8,9,6,6,4])
new=arr.reshape(4,3)
print(new)
print(new.ndim)
print(arr.ndim)


# flattering

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
new= arr.reshape(-1)
print(new)

# numpy iteration

import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in arr:
    print(x)

import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[21,32,44,56],[56,3,76,9]]])
for x in np.nditer(arr):
    print(x)

# numpy joining array

import numpy as np
arr1=np.array([12,13,14])
arr2=np.array([25,45,6,7])
arr=np.concatenate((arr1,arr2))
arr3=np.concatenate((arr1,arr2),axis=0)
print(arr3)

import numpy as np
arr1=np.array([[12,13,14],[54,76,89]])
arr2=np.array([[25,45,6],[45,55,33]])
arr3=np.concatenate((arr1,arr2),axis=1)#columns
arr4=np.concatenate((arr1,arr2),axis=0)#row
print(arr3)
print("printing ....")
print(arr4)

# joining array using stack functions

stacking (ROW)

import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

# hstack()

numpy provides a helper function hstack() to stack along rows

import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

# spliting numpy array

spiliting is reverse operations of joining .
we use array_ spilit() for spliting array.

import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

# array searching

you can search an array for a certain value and return the index that gets a match.

import numpy as np
arr=np.array([1,2,3,4,4,4,4])
x=np.where(arr==4)
print(x)

arr=np.array([1,2,3,4,5,67,8,9])
x=np.where(arr%2==0)
print(x)
print(arr[x])

arr=np.array([1,2,3,4,5,67,8,9])
x=np.where(arr%2==0)
print(x)
print("printing index....")


# searchsorted

there is a method searchsorted() which performs a binary search
in the array and return the index where the specifed value would 
be inserted to maintain the search order.

arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

# sorting array

sorting means putting elements in an ordered sequencs .sort() that will sort a specified array.
this method return a copy of the array leaving the original array unchanged.

arr=np.array([3,2,0,1])
print(np.sort(arr))

arr=np.array(["apple","banana","gauvaa","cherry"])
print(np.sort(arr))

arr=np.array([[2,4,3,6],[5,3,2,0]])
print(np.sort(arr))

# filtering array

arr=np.array([32,65,87,45])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

